### ISSUE TITLE
sampler standalone working differently from standard sampler?

### ISSUE THREAD

**Issue by brucou** [TylorS/most-sample#7]
I ran into some troubles when using the standalone sample package. Basically both `sample` versions have slightly different semantics when it comes to order of subscription. For the standalone sampler, the sampler is subscribed to first, then the source.

```
run (sink, scheduler) {
    const sampleSink = new SampleSink(this.f, this.source, sink)
    const samplerDisposable = this.sampler.run(sampleSink, scheduler)
    const sourceDisposable = this.source.run(sampleSink.hold, scheduler)

    return new SampleDisposable(samplerDisposable, sourceDisposable)
}
```

while in the other `sample` it seems that the source is connected to first :
```
Sampler.prototype.run = function (sink, scheduler) {
  var l = this.sources.length
  var disposables = new Array(l + 1)
  var sinks = new Array(l)

  var sampleSink = new SampleSink(this.f, sinks, sink)

  for (var hold, i = 0; i < l; ++i) {
    hold = sinks[i] = new Hold(sampleSink)
    disposables[i] = this.sources[i].run(hold, scheduler)
  }

  disposables[i] = this.sampler.run(sampleSink, scheduler)

  return dispose.all(disposables)
}
```

That lead to unexpected behavior on a higher combinator that I am working on. I was able to work around this in two ways, either by directly modifying the standalone `sample` code to reestablish the desired order, or by forcing the source to connect first, by using `drain`. Both solutions are sub-optimal however (drain probably means I duplicate flows?, and direct modification of the source code means that a fresh npm install wont get the right version). 

What do you recommend : 
- forking the standalone operator and npm it under another name?
- harmonize the two `sample` operators?

**Comment by TylorS** [comment]
Could you provide a test case where this isn't working correctly? 
The ordering of subscriptions shouldn't matter, all "non sampler" values are remembered internally.

It's important to note that the API is actually different. The function `f` passed to the `sample` in the library **also** receives the value of the `sampler` as the first argument.

``` js
// standard most sample
import { sample } from 'most'

sample(f, sampler, source)

function f (sourceValue) { ... }
```

``` js
// this library
import { sample } from '@most/sample'

sample(f, sampler, source)

function f(samplerValue, sourceValue) { ... }
```

**Comment by brucou** [comment]
True, I haven't even noticed that. Then I guess they should be named differently if they do different things. I do have a test case which is what I am working on, but that will be hard to isolate. I'll be looking for the repo now. Branch is [here](https://github.com/SparksNetwork/sparks-frontend/tree/forgot-password-new-most-subject-experiment), bundled with `webpack --config .config/webpack.unit-test-browser.js --watch` and to open in a browser `http://localhost:63342/sparks-frontend/src/utils/testing/unit-tests.html` with a local webserver. Other possibility is a zoom session.

File where `sample` is used and  `drain` work-around here : 
- `src\higher-order-components\combinators\Switch.ts`

When running tests, with a correct execution, you should see 

```
Testing Switch component
edge cases - no children - switch on source ‣
main cases - 1 child - switch on source - one case206ms ‣
main cases - 2 children - switch on condition - two cases193ms
```

Actual execution, 

```
Testing Switch component
edge cases - no children - switch on source ‣
main cases - 1 child - switch on source - one case206ms ‣
main cases - 2 children - switch on condition - timer (2000ms) expired
```

Also, about `The ordering of subscriptions shouldn't matter, all "non sampler" values are remembered internally.`, because there is a `switch` operator used, my best guess is the remembered values are not remembered because the corresponding stream has terminated. My hunch is such because this is a direct port from Rxjs version where I use `withLatestFrom`, and those would be the only variations in semantics I can think about.

**Comment by briancavalier** [comment]
Thanks @brucou, I hadn't noticed that the `run` order is different in the two implementations.  It likely won't matter in many cases, but perhaps there is a subtle difference that can matter in some cases.  For example, sampling streams that are very fast is tricky, in general.

If you can create a smaller test case that seems to produce a problem, we can certainly dig in.
